started to work on issues identified by shellcheck

diff --git a/counterpart b/counterpart
--- a/counterpart
+++ b/counterpart
@@ -62,33 +62,34 @@
 exclusions=(".Trash" ".Trashes" ".Spotlight-*/" ".DocumentRevisions-*/" "/.fseventsd" "/.hotfiles.btree" "/private/var/db/dyld/dyld_*" "/System/Library/Caches/com.apple.bootstamps/*" "/System/Library/Caches/com.apple.corestorage/*" "/System/Library/Caches/com.apple.kext.caches/*" "/Library/Caches/*" "/Volumes/*" "/dev/*" "/automount" "/Network" "/.vol/*" "/net" "/private/var/folders/*" "/private/var/vm/*" "/private/tmp/*" "/cores")
 loggingDirectory="/Library/Logs/Counterpart/"
 pathToRsync="$(which rsync)"
-pathToRsync="$(ls /opt/local/bin/rsync /usr/local/bin/rsync $pathToRsync 2>/dev/null | head -n 1)"
+pathToRsync="$(find /opt/local/bin /usr/local/bin "$pathToRsync" -name rsync 2>/dev/null | head -n 1)"
 serverBackupPath="/var/backups/counterpart" # this is the path that server data will be backed up to if the -b option is specified
 version="1.3"
 params="-D --inplace --crtimes --acls --archive --delete --delete-excluded $excludeString --hard-links --hfs-compression --one-file-system --protect-decmpfs --verbose"
 # --hfs-compression implies --xattrs --fileflags
 
-# default macports and homebrew install paths
-pathToRsync=`which rsync`
-pathToRsync=`ls /opt/local/bin/rsync /usr/local/bin/rsync $pathToRsync 2>/dev/null | head -n 1`
-
 # functions
 function counterpart_log {
 	# create our log directory if required
 	if [ ! -d "$loggingDirectory" ]; then
-	  mkdir $loggingDirectory
+	  mkdir -p $loggingDirectory
 	fi
-	echo  `/bin/date +"%b %d %T"`" Counterpart[$$]: $1" | tee -a $logPath
+	touch "$logPath" > /dev/null 2>&1
+	if [ ! -w "$logPath" ]; then
+		echo "Logging error: can't write '$1' to '$logPath'"
+	else
+		echo "$(/bin/date +'%b %d %T') Counterpart[$$]: $1" | tee -a "$logPath"
+	fi
 }
 function counterpart_exit {
 	if [ "$1" == "" ]; then
 		1="-99" # rsync crashed with no exit code. have seen this trigger in some disk malfunction scenarios.
 	fi
 	counterpart_log "Counterpart exited with code $1."
-	exit $1
+	exit "$1"
 }
 function counterpart_error {
-	echo $1 > "$dst/.$organisationPrefix.counterpart.error"
+	echo "$1" > "$dst/.$organisationPrefix.counterpart.error"
 	if [ -r "$dst/.$organisationPrefix.counterpart.completed" ]; then
 		rm "$dst/.$organisationPrefix.counterpart.completed"
 	fi
@@ -101,7 +102,7 @@ function counterpart_parse_errors {
 	elif [ ! -w "$dst" ]; then
 		counterpart_log "The destination disappeared/unmounted before the clone could be completed."
 		counterpart_exit 72
-	elif echo $results | grep -q "unpack_smb_acl: sys_acl_get_info(): Undefined error: 0 (0)"; then
+	elif echo "$results" | grep -q "unpack_smb_acl: sys_acl_get_info(): Undefined error: 0 (0)"; then
 		counterpart_log "rsync did not copy a file/directory with an ACE referencing an unknown user. (solution: http://jedda.me/aclfix)"
 		counterpart_error "clone from $src did not complete due to a file/directory with an ACE referencing an unknown user"
 		counterpart_exit 73
@@ -110,11 +111,13 @@ function counterpart_parse_errors {
 function counterpart_generate_stats {
 	# write out the stats file
 	echo "Clone Started: $startTimestamp" > "$dst/.$organisationPrefix.counterpart.stats"
-	echo $results | grep -E -o "Number of files: ([0-9]+)" >> "$dst/.$organisationPrefix.counterpart.stats"
-	echo $results | grep -E -o "Number of files transferred: ([0-9]+)" >> "$dst/.$organisationPrefix.counterpart.stats"
-	echo $results | grep -E -o "Total file size: ([0-9]+) bytes" >> "$dst/.$organisationPrefix.counterpart.stats"
-	echo $results | grep -E -o "Total transferred file size: ([0-9]+) bytes" >> "$dst/.$organisationPrefix.counterpart.stats"
-	echo "Clone Completed: "`/bin/date +%s` >> "$dst/.$organisationPrefix.counterpart.stats"
+	{
+	echo "$results" | grep -E -o "Number of files: ([0-9]+)"
+	echo "$results" | grep -E -o "Number of files transferred: ([0-9]+)" 
+	echo "$results" | grep -E -o "Total file size: ([0-9]+) bytes"
+	echo "$results" | grep -E -o "Total transferred file size: ([0-9]+) bytes"
+	echo "Clone Completed: $(/bin/date +%s)"
+	} >> "$dst/.$organisationPrefix.counterpart.stats"
 	counterpart_log "Saved rsync stats to $dst/.$organisationPrefix.counterpart.stats"
 }
 function backup_postgres {
@@ -256,16 +259,12 @@ printf "Support & Updates:\nFor support, bug reports, answers and updates, see h
 exit 0
 fi
 
-counterpart_log "Setting up our start timestamp and log file, and any other script variables..."
 startTimestamp=$(/bin/date +%s)
 logPath=$loggingDirectory"Counterpart_"`/bin/date -r $startTimestamp +%y-%m-%d_%H-%M-%S`
 host=$(hostname)
 osVersion=$(sw_vers | awk '/ProductVersion/{print substr($2,1,4)}' | tr -d ".")
 rsyncVersion=$($pathToRsync --version | grep 'version' | sed -E 's/ version ([0-9\.]+).+/\1/')
-
-counterpart_log "Checking that we are running as root..."
-if [[ $EUID -ne 0 ]]
-then
+if [[ $EUID -ne 0 ]]; then
 	echo "ERROR - Counterpart must be run as root."
 	exit 1
 fi
@@ -278,11 +277,11 @@ elif ! $pathToRsync --version | grep -q -E -o "version 3"; then
 	counterpart_log "Counterpart requires rsync version 3.0.9 or higher. Follow the instructions at http://jedda.me/counterpart/install to install the required version of rsync before running Counterpart."
 	counterpart_exit 86
 fi
-result=$($pathToRsync -n ${params} . . 2>&1) 
+results=$($pathToRsync -n ${params} . . 2>&1) 
 rsyncExitCode=$?
 if [ "$rsyncExitCode" -ne "0" ]; then
  counterpart_log "rsync parameter: $params"
- counterpart_log "rsync error: `echo $result | tr '\n' ' '`"
+ counterpart_log "rsync error: `echo $results | tr '\n' ' '`"
  counterpart_log "Counterpart requires rsync with some patches enabled. Please run 'counterpart-install-rsync.sh'."
  counterpart_exit 87
 fi
