enhanced test for correct rsync, being more verbose, cleanup, version 1.3

diff --git a/counterpart b/counterpart
--- a/counterpart
+++ b/counterpart
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+#
 #	Counterpart
 #	by Jedda Wignall
 #	http://jedda.me/counterpart
@@ -7,6 +7,11 @@
 #	A wrapper script for rsync 3.0+ that is capable of producing a bootable clone of a live Mac OS X system.
 #	Features extensive error reporting, automatic logging and stats generation.
 
+#   v1.3 - 28 February 2018
+#   Enhanced test for correct rsync version (and added script to install the correct one)
+#   Ensure that ownership is not ignored (otherwise the backup would not be bootable)
+#   More verbose output and general cleanup
+#
 #	v1.2.1 - 16 April 2014
 #	Added the optional flag -g which allows supply of an organisation prefix in reverse domain notation at runtime, rather than editing the script itself.
 #	Fixed issue with date parsing when GNU date is installed by hardcoding BSD /bin/date as per [https://github.com/jedda/Counterpart/issues/4] (thanks jhegeman!)
@@ -42,7 +47,8 @@ exclusions=(".Trash" ".Trashes" ".Spotlight-*/" ".DocumentRevisions-*/" "/.fseve
 loggingDirectory="/Library/Logs/Counterpart/"
 pathToRsync="/usr/local/bin/rsync" # this is the default homebrew installed path
 serverBackupPath="/var/backups/counterpart" # this is the path that server data will be backed up to if the -b option is specified
-version="1.2.1"
+version="1.3"
+params="--acls --archive --delete --delete-excluded $excludeString --hard-links --hfs-compression --one-file-system --protect-decmpfs --sparse --verbose --xattrs"
 
 # functions
 function counterpart_log {
@@ -208,21 +214,21 @@ printf "Support & Updates:\nFor support, bug reports, answers and updates, see h
 exit 0
 fi
 
-# setup our start timestamp and log file, and any other script variables
+counterpart_log "setting up our start timestamp and log file, and any other script variables"
 startTimestamp=$(/bin/date +%s)
 logPath=$loggingDirectory"Counterpart_"`/bin/date -r $startTimestamp +%y-%m-%d_%H-%M-%S`
 host=$(hostname)
 osVersion=$(sw_vers | awk '/ProductVersion/{print substr($2,1,4)}' | tr -d ".")
-rsyncVersion=$(/usr/local/bin/rsync --version | grep 'version' | sed -E 's/ version ([0-9\.]+).+/\1/')
+rsyncVersion=$($pathToRsync --version | grep 'version' | sed -E 's/ version ([0-9\.]+).+/\1/')
 
-# check that we are running as root.
+counterpart_log "check that we are running as root"
 if [[ $EUID -ne 0 ]]
 then
 	echo "ERROR - Counterpart must be run as root."
 	exit 1
 fi
 
-# check that have the right version of rsync installed
+counterpart_log "checking that have the right version of rsync installed"
 if [ ! -x "$pathToRsync" ]; then
 	counterpart_log "rsync does not exist (or is not executable) at $pathToRsync. Follow the instructions at http://jedda.me/counterpart/install to install the required version of rsync before running Counterpart."
 	counterpart_exit 85
@@ -230,25 +236,33 @@ elif ! $pathToRsync --version | grep -q -E -o "version 3"; then
 	counterpart_log "Counterpart requires rsync version 3.0.9 or higher. Follow the instructions at http://jedda.me/counterpart/install to install the required version of rsync before running Counterpart."
 	counterpart_exit 86
 fi
+result=$($pathToRsync -n ${params} . . 2>&1) 
+rsyncExitCode=$?
+if [ "$rsyncExitCode" -ne "0" ]; then
+ counterpart_log "rsync parameter: $params"
+ counterpart_log "rsync error: `echo $result | tr '\n' ' '`"
+ counterpart_log "Counterpart requires rsync with some patches enabled. Please run 'counterpart-install-rsync.sh'."
+ counterpart_exit 87
+fi
 
-# set our default organisation prefix if one has not been supplied
+counterpart_log "setting our default organisation prefix if one has not been supplied"
 if [ "$organisationPrefix" == "" ]; then
 organisationPrefix="me.jedda"
 fi
 
-# introduce ourselves
+counterpart_log "introducing ourselves"
 counterpart_log "Counterpart version $version (`md5 $0 | awk '{ print substr($4,0,6) }'`)."
 counterpart_log "Logging to $logPath."
 counterpart_log "Output files will have the prefix $organisationPrefix.counterpart."
 counterpart_log "Running on $host (`sw_vers | awk '/ProductVersion/{print substr($2,1,6)}'`) with $rsyncVersion at $pathToRsync."
 
-# check that source is defined
+counterpart_log "check that source is defined"
 if [ "$src" == "" ]; then
 	counterpart_log "Source not defined. Cannot continue with the clone process."
 	counterpart_exit 2
 fi
 
-# check that destination is defined
+counterpart_log "check that destination is defined"
 if [ "$dst" == "" ]; then
 	counterpart_log "Destination not defined. Cannot continue with the clone process."
 	counterpart_exit 2
@@ -256,27 +270,23 @@ fi
 
 counterpart_log "Initialising clone from $src to $dst."
 
-# check that the source is readable
+counterpart_log "check that the source is readable"
 if [ ! -r "$src" ]; then
 	counterpart_log "Source ($src) is not readable. Cannot continue with the clone process."
 	counterpart_error "source ($src) not readable"
     counterpart_exit 65
 fi
 
-# check that the destination is writable
+counterpart_log "check that the destination is writable"
 if [ ! -w "$dst" ]; then
 	counterpart_log "Destination ($dst) is not writable. Cannot continue with the clone process."
     counterpart_exit 66
 fi
 
-# check that the destination is not set to ignore ownership
-vsdbOutput=$(/usr/sbin/vsdbutil -c "$dst")
-if echo $vsdbOutput | grep -q -E -o "disabled"; then
-	counterpart_log "Destination ($dst) is set to 'Ignore ownership on this volume'. Volume will not be bootable! Cannot continue with the clone process."
-    counterpart_exit 90
-fi
+counterpart_log "Ensuring that the destination is not ignoring ownership..."
+/usr/sbin/vsdbutil -a "${dst}"
 
-# build our exclusions string
+counterpart_log "building our exclusions string"
 for exc in "${exclusions[@]}"
 do
   excludeString="$excludeString--exclude=$exc "
@@ -292,14 +302,14 @@ if [ "$excludeFrom" != "" ]; then
 	fi
 fi
 
-# check to see if this is a test run
+counterpart_log "checking to see if this is a test run"
 if [ "$testRun" == "true" ]; then
 	counterpart_log "Test option specified. Performing a test run - will log all output below:"
-	$pathToRsync -n --acls --archive --delete --delete-excluded $excludeString --hard-links --hfs-compression --one-file-system --protect-decmpfs --sparse --verbose --xattrs "$src" "$dst" 2>&1 | tee -a $logPath
+	$pathToRsync -n ${params} "$src" "$dst" 2>&1 | tee -a $logPath
 	counterpart_exit 70
 fi
 
-# check to see if we need to execute an os x server backup
+counterpart_log "checking to see if we need to execute an os x server backup"
 if [ "$backup" != "" ]; then
 	if [ ! -d "$serverBackupPath" ]; then
 		mkdir -p $serverBackupPath
@@ -328,7 +338,7 @@ if [ "$backup" != "" ]; then
 	esac
 fi
 
-# check to see if we need to execute a pre-clone script
+counterpart_log "checking to see if we need to execute a pre-clone script"
 if [ "$pre" != "" ]; then
 	if [ ! -x "$pre" ]; then
 		counterpart_log "The pre-clone script at $pre does not exist or could not be executed."
@@ -341,8 +351,8 @@ if [ "$pre" != "" ]; then
 fi
 
 # time to spin up rsync
-counterpart_log "Running rsync clone..."
-results=$($pathToRsync --acls --archive --delete --delete-excluded $excludeString --hard-links --hfs-compression --one-file-system --protect-decmpfs --sparse --stats --xattrs "$src" "$dst" 2>&1)
+counterpart_log "Running rsync clone now..."
+results=$($pathToRsync ${params} "$src" "$dst" 2>&1)
 rsyncExitCode=$?
 
 # handle the rsync exit code
@@ -393,7 +403,7 @@ case "$rsyncExitCode" in
 			;;
 esac
 
-# check to see if we need to execute a post-clone script
+counterpart_log "checking to see if we need to execute a post-clone script"
 if [ "$post" != "" ]; then
 	if [ ! -x "$post" ]; then
 		counterpart_log "The post-clone script at $post does not exist or could not be executed."
